import { NextResponse } from 'next/server'
// Import the generated JSON file directly
// Note: This file is generated by scripts/csv-to-json.js before build
import timetableData from '../../../data/timetable.json'

export async function GET() {
  try {
    // Return the static JSON data
    return NextResponse.json(timetableData)
  } catch (error) {
    console.error('Error reading timetable:', error)
    return NextResponse.json({ error: 'Failed to load timetable data' }, { status: 500 })
  }
}